import type { Metadata } from "next";
import { Cart } from "@/components/cart";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="h-16 w-full bg-black">
          <h1>LOGO</h1>
          <Cart />
        </nav>
          {children}
        <footer className="">
          <p>© 2024 Footer</p>
        </footer>
      </body>
      
    </html>
  );
}
