/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShoppingCartImport } from './routes/shoppingCart'
import { Route as IndexImport } from './routes/index'
import { Route as MenuIndexImport } from './routes/menu/index'
import { Route as MenuSlugImport } from './routes/menu/$slug'

// Create/Update Routes

const ShoppingCartRoute = ShoppingCartImport.update({
  id: '/shoppingCart',
  path: '/shoppingCart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MenuIndexRoute = MenuIndexImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRoute,
} as any)

const MenuSlugRoute = MenuSlugImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/shoppingCart': {
      id: '/shoppingCart'
      path: '/shoppingCart'
      fullPath: '/shoppingCart'
      preLoaderRoute: typeof ShoppingCartImport
      parentRoute: typeof rootRoute
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugImport
      parentRoute: typeof rootRoute
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shoppingCart': typeof ShoppingCartRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/menu': typeof MenuIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shoppingCart': typeof ShoppingCartRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/menu': typeof MenuIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/shoppingCart': typeof ShoppingCartRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/menu/': typeof MenuIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shoppingCart' | '/menu/$slug' | '/menu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shoppingCart' | '/menu/$slug' | '/menu'
  id: '__root__' | '/' | '/shoppingCart' | '/menu/$slug' | '/menu/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShoppingCartRoute: typeof ShoppingCartRoute
  MenuSlugRoute: typeof MenuSlugRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShoppingCartRoute: ShoppingCartRoute,
  MenuSlugRoute: MenuSlugRoute,
  MenuIndexRoute: MenuIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/shoppingCart",
        "/menu/$slug",
        "/menu/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/shoppingCart": {
      "filePath": "shoppingCart.tsx"
    },
    "/menu/$slug": {
      "filePath": "menu/$slug.tsx"
    },
    "/menu/": {
      "filePath": "menu/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
