/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
<<<<<<< HEAD
=======
import { Route as ShoppingCartImport } from './routes/shoppingCart'
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
import { Route as MenuImport } from './routes/menu'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

<<<<<<< HEAD
=======
const ShoppingCartRoute = ShoppingCartImport.update({
  id: '/shoppingCart',
  path: '/shoppingCart',
  getParentRoute: () => rootRoute,
} as any)

>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
const MenuRoute = MenuImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuImport
<<<<<<< HEAD
=======
      parentRoute: typeof rootRoute
    }
    '/shoppingCart': {
      id: '/shoppingCart'
      path: '/shoppingCart'
      fullPath: '/shoppingCart'
      preLoaderRoute: typeof ShoppingCartImport
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
<<<<<<< HEAD
=======
  '/shoppingCart': typeof ShoppingCartRoute
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
<<<<<<< HEAD
=======
  '/shoppingCart': typeof ShoppingCartRoute
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
<<<<<<< HEAD
=======
  '/shoppingCart': typeof ShoppingCartRoute
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths: '/' | '/menu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menu'
  id: '__root__' | '/' | '/menu'
=======
  fullPaths: '/' | '/menu' | '/shoppingCart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menu' | '/shoppingCart'
  id: '__root__' | '/' | '/menu' | '/shoppingCart'
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRoute: typeof MenuRoute
<<<<<<< HEAD
=======
  ShoppingCartRoute: typeof ShoppingCartRoute
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
<<<<<<< HEAD
=======
  ShoppingCartRoute: ShoppingCartRoute,
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
<<<<<<< HEAD
        "/menu"
=======
        "/menu",
        "/shoppingCart"
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/menu": {
      "filePath": "menu.tsx"
<<<<<<< HEAD
=======
    },
    "/shoppingCart": {
      "filePath": "shoppingCart.tsx"
>>>>>>> 523d4d01fd73ec5ac2247f74577eeca5704c5ba3
    }
  }
}
ROUTE_MANIFEST_END */
